### PR TITLE
[Bundle] devices subdevices.endpoint attribute

### PR DESCRIPTION
**Pull request by Zehir**
This PR is a draft to discuss about changes to do for the DDF bundles.

To be able to fully use the /devices endpoint to do stuff we need a way to send requests that do something.
Until (if there is plan for it) the api have endpoints to update config, name, ...

It's would be a nice workaround to map the data returned by the `/devices/<device_mac_address>` endpoint.

So I suggest to add to the API inside the `subdevices` array a new `endpoint` property. The value will be with the format `/[sensors/lights]/[subdeviceID]` ex : `/sensors/1`

This is to solve the issue where from the data you get with the endpoint you have no way to find the device except by reading a full state and search for the subdevice.

### CODE REVIEW

**Comment by manup** [comment]
If I understand this right this is already supported. The full sensor `uniqueid` which is exposed via `/devices` endpoint, can be used by `/sensors/<uniqueid>`. Imho that's also a better way than using the short `id` for references as it is stable even if the device is deleted and re-paired.

**Comment by Zehir** [comment]
Wait what, since when this is a thing ! Oo
This need to be  documented but there is still a problem, how do I know if I need to use the `/lights` or the `/sensors` endpoint ? Based on the device type ?
There is not many types in light so anything that is not a light is a sensor ?

**Comment by Zehir** [comment]
I was more thinking of a `writable` equivalent of `GET /api/<apikey>/devices/<uniqueid>/<prefix>/<item>/introspect`

**Comment by manup** [comment]
>Wait what, since when this is a thing ! Oo

Since a very long time :) but yeah could be missing in the docs since this was an addition after the initial version which only supported short `id` values. The reason to add it was to support specifying the full `uniqueid` in rules, so they keep being valid even if devices are deleted and rejoined.

>This need to be documented but there is still a problem, how do I know if I need to use the /lights or the /sensors endpoint ? Based on the device type ?
There is not many types in light so anything that is not a light is a sensor ?

It's not yet exposed in the `/devices` endpoint but, each DDF subdevice has the `restapi` key for this very purpose to construct full URLs to address them via legacy paths. I'll expose this soon so it can be used.

>BTW the uniqueid here need to have the full "path" like 00:11:22:33:44:55:66:77-01-0006 and not only 00:11:22:33:44:55:66:77, maybe we need to add that in the doc ?

Indeed it only works for sub-devices and their respective full uniqueids.

>And if the introspect result could return the info if the value is writable or not

We could do that, but it will be deprecated from the beginning ;)
Later on I hope to get rid of all "direct writes" to attributes, and replace them with proper method/messaging interface which is also dynamically constructed like the DDFs but for the REST-API itself.

**Comment by Zehir** [comment]
> > BTW the uniqueid here need to have the full "path" like 00:11:22:33:44:55:66:77-01-0006 and not only 00:11:22:33:44:55:66:77, maybe we need to add that in the doc ?
> 
> Indeed it only works for sub-devices and their respective full uniqueids.
> 
> > And if the introspect result could return the info if the value is writable or not
> 
> We could do that, but it will be deprecated from the beginning ;) Later on I hope to get rid of all "direct writes" to attributes, and replace them with proper method/messaging interface which is also dynamically constructed like the DDFs but for the REST-API itself.

Yes but that could take many years before it's ready ?

**Comment by Zehir** [comment]
So it's a no

**Pull request closed without merging**
