### PR TITLE
Update configuration endpoint documentation

### PR DESCRIPTION
**Pull request by Zehir**
This pull request updates the documentation for the configuration endpoint. Specifically, it changes the description of the "gateway" field to clarify that it refers to the IPv4 network gateway of the gateway.
It also updates the "softwareupdate" field to "swupdate2" to align with the actual object name.
Additionally, it corrects the endpoint URL for resetting the password.

### CODE REVIEW

**Comment by Zehir** [comment]
Fix for #19

**Comment by Zehir** [comment]
Fix for #20

**Comment by Zehir** [comment]
@manup can you close the 2 mentioned issues above ?

**Comment by manup** [comment]
Done :)

**Pull request merged**
